# CMake generated Testfile for 
# Source directory: C:/Users/vande/Desktop/loxboot
# Build directory: C:/Users/vande/Desktop/loxboot/build_msvc_uart
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_crc32 "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_crc32.exe")
  set_tests_properties(test_loxboot_crc32 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_crc32 "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_crc32.exe")
  set_tests_properties(test_loxboot_crc32 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_crc32 "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_crc32.exe")
  set_tests_properties(test_loxboot_crc32 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_crc32 "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_crc32.exe")
  set_tests_properties(test_loxboot_crc32 PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_crc32 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_init "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_init.exe")
  set_tests_properties(test_loxboot_init PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_init "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_init.exe")
  set_tests_properties(test_loxboot_init PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_init "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_init.exe")
  set_tests_properties(test_loxboot_init PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_init "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_init.exe")
  set_tests_properties(test_loxboot_init PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_init NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_slot_state "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_slot_state.exe")
  set_tests_properties(test_loxboot_slot_state PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_slot_state "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_slot_state.exe")
  set_tests_properties(test_loxboot_slot_state PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_slot_state "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_slot_state.exe")
  set_tests_properties(test_loxboot_slot_state PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_slot_state "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_slot_state.exe")
  set_tests_properties(test_loxboot_slot_state PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_slot_state NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_commit_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_commit_slot.exe")
  set_tests_properties(test_loxboot_commit_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_commit_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_commit_slot.exe")
  set_tests_properties(test_loxboot_commit_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_commit_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_commit_slot.exe")
  set_tests_properties(test_loxboot_commit_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_commit_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_commit_slot.exe")
  set_tests_properties(test_loxboot_commit_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_commit_slot NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_invalidate_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_invalidate_slot.exe")
  set_tests_properties(test_loxboot_invalidate_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_invalidate_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_invalidate_slot.exe")
  set_tests_properties(test_loxboot_invalidate_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_invalidate_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_invalidate_slot.exe")
  set_tests_properties(test_loxboot_invalidate_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_invalidate_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_invalidate_slot.exe")
  set_tests_properties(test_loxboot_invalidate_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_invalidate_slot NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_confirm_boot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_confirm_boot.exe")
  set_tests_properties(test_loxboot_confirm_boot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_confirm_boot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_confirm_boot.exe")
  set_tests_properties(test_loxboot_confirm_boot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_confirm_boot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_confirm_boot.exe")
  set_tests_properties(test_loxboot_confirm_boot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_confirm_boot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_confirm_boot.exe")
  set_tests_properties(test_loxboot_confirm_boot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_confirm_boot NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_request_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_request_slot.exe")
  set_tests_properties(test_loxboot_request_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_request_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_request_slot.exe")
  set_tests_properties(test_loxboot_request_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_request_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_request_slot.exe")
  set_tests_properties(test_loxboot_request_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_request_slot "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_request_slot.exe")
  set_tests_properties(test_loxboot_request_slot PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_request_slot NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_state_edges "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_state_edges.exe")
  set_tests_properties(test_loxboot_state_edges PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_state_edges "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_state_edges.exe")
  set_tests_properties(test_loxboot_state_edges PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_state_edges "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_state_edges.exe")
  set_tests_properties(test_loxboot_state_edges PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_state_edges "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_state_edges.exe")
  set_tests_properties(test_loxboot_state_edges PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_state_edges NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_boot_sequence "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_boot_sequence.exe")
  set_tests_properties(test_loxboot_boot_sequence PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_boot_sequence "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_boot_sequence.exe")
  set_tests_properties(test_loxboot_boot_sequence PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_boot_sequence "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_boot_sequence.exe")
  set_tests_properties(test_loxboot_boot_sequence PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_boot_sequence "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_boot_sequence.exe")
  set_tests_properties(test_loxboot_boot_sequence PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_boot_sequence NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_rollback "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_rollback.exe")
  set_tests_properties(test_loxboot_rollback PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_rollback "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_rollback.exe")
  set_tests_properties(test_loxboot_rollback PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_rollback "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_rollback.exe")
  set_tests_properties(test_loxboot_rollback PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_rollback "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_rollback.exe")
  set_tests_properties(test_loxboot_rollback PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_rollback NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_crash_loop "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_crash_loop.exe")
  set_tests_properties(test_loxboot_crash_loop PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_crash_loop "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_crash_loop.exe")
  set_tests_properties(test_loxboot_crash_loop PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_crash_loop "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_crash_loop.exe")
  set_tests_properties(test_loxboot_crash_loop PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_crash_loop "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_crash_loop.exe")
  set_tests_properties(test_loxboot_crash_loop PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_crash_loop NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_uart_frame "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_uart_frame.exe")
  set_tests_properties(test_loxboot_uart_frame PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_uart_frame "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_uart_frame.exe")
  set_tests_properties(test_loxboot_uart_frame PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_uart_frame "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_uart_frame.exe")
  set_tests_properties(test_loxboot_uart_frame PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_uart_frame "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_uart_frame.exe")
  set_tests_properties(test_loxboot_uart_frame PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_uart_frame NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_loxboot_uart_receive "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Debug/test_loxboot_uart_receive.exe")
  set_tests_properties(test_loxboot_uart_receive PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_loxboot_uart_receive "C:/Users/vande/Desktop/loxboot/build_msvc_uart/Release/test_loxboot_uart_receive.exe")
  set_tests_properties(test_loxboot_uart_receive PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_loxboot_uart_receive "C:/Users/vande/Desktop/loxboot/build_msvc_uart/MinSizeRel/test_loxboot_uart_receive.exe")
  set_tests_properties(test_loxboot_uart_receive PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_loxboot_uart_receive "C:/Users/vande/Desktop/loxboot/build_msvc_uart/RelWithDebInfo/test_loxboot_uart_receive.exe")
  set_tests_properties(test_loxboot_uart_receive PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxboot/CMakeLists.txt;178;add_test;C:/Users/vande/Desktop/loxboot/CMakeLists.txt;0;")
else()
  add_test(test_loxboot_uart_receive NOT_AVAILABLE)
endif()
