#ifndef LOXBOOT_VERSION_H
#define LOXBOOT_VERSION_H

#define LOXBOOT_VERSION_MAJOR 0
#define LOXBOOT_VERSION_MINOR 2
#define LOXBOOT_VERSION_PATCH 0

#define LOXBOOT_VERSION_STRING "0.2.0"

#endif /* LOXBOOT_VERSION_H */
